// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zippy.Cash.Repository;

#nullable disable

namespace Zippy.Cash.Repository.Migrations
{
    [DbContext(typeof(ZippyDBContext))]
    [Migration("20211203155250_VerificationStatuses_DocumentTypes_Documents")]
    partial class VerificationStatuses_DocumentTypes_Documents
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Zippy.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = "8aef45d2-1b8d-4f20-b58c-7abaffca99ba",
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2598),
                            OwnerId = 1,
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2598)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Zippy.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Zippy.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2850),
                            Name = "United States",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2850)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2852),
                            Name = "Canada",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2852)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2969),
                            Name = "USD",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2969)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2972),
                            Name = "CAD",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(2972)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Document", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("EntityId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("VerificationStatusId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("TypeId");

                    b.HasIndex("VerificationStatusId");

                    b.ToTable("Documents");
                });

            modelBuilder.Entity("Zippy.Model.DocumentType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("DocumentTypes");
                });

            modelBuilder.Entity("Zippy.Model.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organization", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = "",
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3039),
                            Name = "Zippy",
                            TaxID = "",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3039)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3131),
                            Name = "Ontario",
                            RegionCode = "001",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3131)
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3133),
                            Name = "Manitoba",
                            RegionCode = "002",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3133)
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3135),
                            Name = "Quebec",
                            RegionCode = "003",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 15, 52, 49, 813, DateTimeKind.Utc).AddTicks(3135)
                        });
                });

            modelBuilder.Entity("Zippy.Model.VerificationStatus", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("VerificationStatuses");
                });

            modelBuilder.Entity("Zippy.Model.Document", b =>
                {
                    b.HasOne("Zippy.Model.DocumentType", "DocumentType")
                        .WithMany("Documents")
                        .HasForeignKey("TypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Zippy.Model.VerificationStatus", "VerificationStatus")
                        .WithMany("Documents")
                        .HasForeignKey("VerificationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DocumentType");

                    b.Navigation("VerificationStatus");
                });

            modelBuilder.Entity("Zippy.Model.Region", b =>
                {
                    b.HasOne("Zippy.Model.Country", null)
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zippy.Model.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Zippy.Model.DocumentType", b =>
                {
                    b.Navigation("Documents");
                });

            modelBuilder.Entity("Zippy.Model.VerificationStatus", b =>
                {
                    b.Navigation("Documents");
                });
#pragma warning restore 612, 618
        }
    }
}
