// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zippy.Cash.Repository;

#nullable disable

namespace Zippy.Cash.Repository.Migrations
{
    [DbContext(typeof(ZippyDBContext))]
    [Migration("20211203170218_ProcessingChannelTypes_ProcessingChannels_CardDetail_FundingSources")]
    partial class ProcessingChannelTypes_ProcessingChannels_CardDetail_FundingSources
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Zippy.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = "05e16863-473a-4428-b40b-6cab195f103c",
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8529),
                            OwnerId = 1,
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8529)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Address", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Address1")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Address2")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("ClientId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("RegionId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Zip")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("Zippy.Model.CardDetail", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Brand")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("ExpirationMonth")
                        .HasColumnType("int");

                    b.Property<int>("ExpriationYear")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("CardDetails");
                });

            modelBuilder.Entity("Zippy.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Zippy.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8766),
                            Name = "United States",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8766)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8767),
                            Name = "Canada",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8768)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8875),
                            Name = "USD",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8875)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8877),
                            Name = "CAD",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8877)
                        });
                });

            modelBuilder.Entity("Zippy.Model.FundingSource", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("BankDetailsId")
                        .HasColumnType("int");

                    b.Property<int>("CardDetailId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("LedgerId")
                        .HasColumnType("int");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("Removed")
                        .HasColumnType("bit");

                    b.Property<int>("SourceId")
                        .HasColumnType("int");

                    b.Property<int>("StatusId")
                        .HasColumnType("int");

                    b.Property<int>("TypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CardDetailId");

                    b.ToTable("FundingSources");
                });

            modelBuilder.Entity("Zippy.Model.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organization", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = "",
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8944),
                            Name = "Zippy",
                            TaxID = "",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(8945)
                        });
                });

            modelBuilder.Entity("Zippy.Model.ProcessingChannel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int?>("FundingSourceId")
                        .HasColumnType("int");

                    b.Property<int?>("ProcessingChannelTypeId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FundingSourceId");

                    b.HasIndex("ProcessingChannelTypeId");

                    b.ToTable("ProcessingChannels");
                });

            modelBuilder.Entity("Zippy.Model.ProcessingChannelType", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ProcessingChannelTypes");
                });

            modelBuilder.Entity("Zippy.Model.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(9039),
                            Name = "Ontario",
                            RegionCode = "001",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(9040)
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(9042),
                            Name = "Manitoba",
                            RegionCode = "002",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(9042)
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(9043),
                            Name = "Quebec",
                            RegionCode = "003",
                            UpdatedOnUTC = new DateTime(2021, 12, 3, 17, 2, 17, 988, DateTimeKind.Utc).AddTicks(9043)
                        });
                });

            modelBuilder.Entity("Zippy.Model.FundingSource", b =>
                {
                    b.HasOne("Zippy.Model.CardDetail", "CardDetail")
                        .WithMany()
                        .HasForeignKey("CardDetailId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CardDetail");
                });

            modelBuilder.Entity("Zippy.Model.ProcessingChannel", b =>
                {
                    b.HasOne("Zippy.Model.FundingSource", null)
                        .WithMany("ProcessingChannels")
                        .HasForeignKey("FundingSourceId");

                    b.HasOne("Zippy.Model.ProcessingChannelType", null)
                        .WithMany("ProcessingChannels")
                        .HasForeignKey("ProcessingChannelTypeId");
                });

            modelBuilder.Entity("Zippy.Model.Region", b =>
                {
                    b.HasOne("Zippy.Model.Country", null)
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zippy.Model.Country", b =>
                {
                    b.Navigation("Regions");
                });

            modelBuilder.Entity("Zippy.Model.FundingSource", b =>
                {
                    b.Navigation("ProcessingChannels");
                });

            modelBuilder.Entity("Zippy.Model.ProcessingChannelType", b =>
                {
                    b.Navigation("ProcessingChannels");
                });
#pragma warning restore 612, 618
        }
    }
}
