// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Zippy.Cash.API.DAL;

#nullable disable

namespace Zippy.Cash.API.Migrations
{
    [DbContext(typeof(ZippyDBContext))]
    [Migration("20211126095416_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Zippy.Model.Account", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<int>("OwnerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Account", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = "9251de9a-5955-48f9-9942-1bb0aac437fe",
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6210),
                            OwnerId = 1,
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6210)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Client", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("OrganizationId")
                        .HasColumnType("int");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PurposeOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TypeOfBusiness")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserToken")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Website")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Client", (string)null);
                });

            modelBuilder.Entity("Zippy.Model.Country", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Country", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6522),
                            Name = "United States",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6522)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6524),
                            Name = "Canada",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6525)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Currency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Currency", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6640),
                            Name = "USD",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6641)
                        },
                        new
                        {
                            Id = 2,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6643),
                            Name = "CAD",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6643)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Organization", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TaxID")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Organization", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            AccountId = "",
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6735),
                            Name = "Zippy",
                            TaxID = "",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6736)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Region", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<int>("CountryId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedOnUTC")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RegionCode")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("UpdatedOnUTC")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("CountryId");

                    b.ToTable("Region", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6869),
                            Name = "Ontario",
                            RegionCode = "001",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6869)
                        },
                        new
                        {
                            Id = 2,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6871),
                            Name = "Manitoba",
                            RegionCode = "002",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6872)
                        },
                        new
                        {
                            Id = 3,
                            CountryId = 2,
                            CreatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6874),
                            Name = "Quebec",
                            RegionCode = "003",
                            UpdatedOnUTC = new DateTime(2021, 11, 26, 9, 54, 15, 951, DateTimeKind.Utc).AddTicks(6874)
                        });
                });

            modelBuilder.Entity("Zippy.Model.Region", b =>
                {
                    b.HasOne("Zippy.Model.Country", null)
                        .WithMany("Regions")
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Zippy.Model.Country", b =>
                {
                    b.Navigation("Regions");
                });
#pragma warning restore 612, 618
        }
    }
}
